import { Employee } from "./employees-list-columns";

export const data: Employee[] = [
  {
    id: "1",
    employeeName: "Alice Johnson",
    employeeId: "E001",
    department: "Engineering",
    designation: "Software Engineer",
    type: "REMOTE",
    status: "PERMANENT", // Example status
  },
  {
    id: "2",
    employeeName: "Bob Smith",
    employeeId: "E002",
    department: "Marketing",
    designation: "Marketing Specialist",
    type: "OFFICE",
    status: "INTERN",
  },
  {
    id: "3",
    employeeName: "Carla Williams",
    employeeId: "E003",
    department: "Human Resources",
    designation: "HR Manager",
    type: "REMOTE",
    status: "PROBATION",
  },
  {
    id: "4",
    employeeName: "David Brown",
    employeeId: "E004",
    department: "Finance",
    designation: "Accountant",
    type: "OFFICE",
    status: "PART_TIME",
  },
  {
    id: "5",
    employeeName: "Ella Davis",
    employeeId: "E005",
    department: "Engineering",
    designation: "Frontend Developer",
    type: "REMOTE",
    status: "TEMPORARY",
  },
  {
    id: "6",
    employeeName: "Frank Miller",
    employeeId: "E006",
    department: "Sales",
    designation: "Sales Executive",
    type: "OFFICE",
    status: "PROBATION",
  },
  {
    id: "7",
    employeeName: "Grace Wilson",
    employeeId: "E007",
    department: "Customer Support",
    designation: "Support Agent",
    type: "REMOTE",
    status: "PART_TIME",
  },
  {
    id: "8",
    employeeName: "Harry Moore",
    employeeId: "E008",
    department: "Engineering",
    designation: "Backend Developer",
    type: "OFFICE",
    status: "PERMANENT",
  },
  {
    id: "9",
    employeeName: "Isla Taylor",
    employeeId: "E009",
    department: "Design",
    designation: "UI/UX Designer",
    type: "REMOTE",
    status: "INTERN",
  },
  {
    id: "10",
    employeeName: "Jack Thomas",
    employeeId: "E010",
    department: "Engineering",
    designation: "DevOps Engineer",
    type: "OFFICE",
    status: "TEMPORARY",
  },
  {
    id: "11",
    employeeName: "Kara Anderson",
    employeeId: "E011",
    department: "Legal",
    designation: "Legal Advisor",
    type: "REMOTE",
    status: "CONTRACT",
  },
  {
    id: "12",
    employeeName: "Liam Scott",
    employeeId: "E012",
    department: "Operations",
    designation: "Operations Manager",
    type: "OFFICE",
    status: "PART_TIME",
  },
  {
    id: "13",
    employeeName: "Mia Martinez",
    employeeId: "E013",
    department: "Engineering",
    designation: "Mobile Developer",
    type: "REMOTE",
    status: "TEMPORARY",
  },
  {
    id: "14",
    employeeName: "Nathan Clark",
    employeeId: "E014",
    department: "Finance",
    designation: "Financial Analyst",
    type: "OFFICE",
    status: "PROBATION",
  },
  {
    id: "15",
    employeeName: "Olivia Lewis",
    employeeId: "E015",
    department: "Customer Support",
    designation: "Customer Success Manager",
    type: "REMOTE",
    status: "INTERN",
  },
  {
    id: "16",
    employeeName: "Paul Young",
    employeeId: "E016",
    department: "Engineering",
    designation: "Data Engineer",
    type: "OFFICE",
    status: "PERMANENT",
  },
  {
    id: "17",
    employeeName: "Quinn Baker",
    employeeId: "E017",
    department: "Sales",
    designation: "Account Manager",
    type: "REMOTE",
    status: "PROBATION",
  },
  {
    id: "18",
    employeeName: "Rachel Green",
    employeeId: "E018",
    department: "Marketing",
    designation: "Content Strategist",
    type: "OFFICE",
    status: "TEMPORARY",
  },
  {
    id: "19",
    employeeName: "Sam White",
    employeeId: "E019",
    department: "Engineering",
    designation: "Security Engineer",
    type: "REMOTE",
    status: "PART_TIME",
  },
  {
    id: "20",
    employeeName: "Tina Black",
    employeeId: "E020",
    department: "Design",
    designation: "Graphic Designer",
    type: "OFFICE",
    status: "INTERN",
  },
];
