import { Candidate } from "./candidates-list-columns";

export const data: Candidate[] = [
  {
    id: "1",
    candidateName: "John Doe",
    appliedFor: "Software Engineer",
    appliedDate: "2024-11-01",
    email: "johndoe@example.com",
    mobileNumber: "+1234567890",
    status: "SELECTED",
  },
  {
    id: "2",
    candidateName: "Alice Smith",
    appliedFor: "Frontend Developer",
    appliedDate: "2024-11-05",
    email: "alicesmith@example.com",
    mobileNumber: "+1987654321",
    status: "IN_PROCESS",
  },
  {
    id: "3",
    candidateName: "Bob Johnson",
    appliedFor: "Backend Developer",
    appliedDate: "2024-10-15",
    email: "bobjohnson@example.com",
    mobileNumber: "+1230987654",
    status: "REJECTED",
  },
  {
    id: "4",
    candidateName: "Emily Davis",
    appliedFor: "Product Manager",
    appliedDate: "2024-09-25",
    email: "emilydavis@example.com",
    mobileNumber: "+1222333444",
    status: "SELECTED",
  },
  {
    id: "5",
    candidateName: "Michael Brown",
    appliedFor: "Data Scientist",
    appliedDate: "2024-11-10",
    email: "michaelbrown@example.com",
    mobileNumber: "+1345678901",
    status: "IN_PROCESS",
  },
  {
    id: "6",
    candidateName: "Sarah Miller",
    appliedFor: "UX Designer",
    appliedDate: "2024-08-20",
    email: "sarahmiller@example.com",
    mobileNumber: "+1456789012",
    status: "REJECTED",
  },
  {
    id: "7",
    candidateName: "James Wilson",
    appliedFor: "DevOps Engineer",
    appliedDate: "2024-11-02",
    email: "jameswilson@example.com",
    mobileNumber: "+1567890123",
    status: "SELECTED",
  },
  {
    id: "8",
    candidateName: "Sophia Taylor",
    appliedFor: "Business Analyst",
    appliedDate: "2024-10-05",
    email: "sophiataylor@example.com",
    mobileNumber: "+1678901234",
    status: "IN_PROCESS",
  },
  {
    id: "9",
    candidateName: "David Martinez",
    appliedFor: "Marketing Specialist",
    appliedDate: "2024-11-12",
    email: "davidmartinez@example.com",
    mobileNumber: "+1789012345",
    status: "REJECTED",
  },
  {
    id: "10",
    candidateName: "Olivia Garcia",
    appliedFor: "Content Writer",
    appliedDate: "2024-11-08",
    email: "oliviagarcia@example.com",
    mobileNumber: "+1890123456",
    status: "SELECTED",
  },
  {
    id: "11",
    candidateName: "Henry Walker",
    appliedFor: "Mobile App Developer",
    appliedDate: "2024-09-10",
    email: "henrywalker@example.com",
    mobileNumber: "+1209876543",
    status: "IN_PROCESS"
  },
  {
    id: "12",
    candidateName: "Charlotte Harris",
    appliedFor: "Frontend Developer",
    appliedDate: "2024-11-03",
    email: "charlotteharris@example.com",
    mobileNumber: "+1308765432",
    status: "REJECTED"
  },
  {
    id: "13",
    candidateName: "Liam Clark",
    appliedFor: "Full Stack Developer",
    appliedDate: "2024-10-30",
    email: "liamclark@example.com",
    mobileNumber: "+1498765432",
    status: "SELECTED"
  },
  {
    id: "14",
    candidateName: "Amelia Lewis",
    appliedFor: "HR Manager",
    appliedDate: "2024-08-15",
    email: "amialewis@example.com",
    mobileNumber: "+1609876543",
    status: "IN_PROCESS"
  },
  {
    id: "15",
    candidateName: "Ethan Young",
    appliedFor: "Software Tester",
    appliedDate: "2024-11-04",
    email: "ethanyoung@example.com",
    mobileNumber: "+1712345678",
    status: "REJECTED"
  },
  {
    id: "16",
    candidateName: "Isabella King",
    appliedFor: "Digital Marketing Specialist",
    appliedDate: "2024-09-19",
    email: "isabellaking@example.com",
    mobileNumber: "+1823456789",
    status: "SELECTED"
  },
  {
    id: "17",
    candidateName: "Matthew Scott",
    appliedFor: "Network Engineer",
    appliedDate: "2024-11-07",
    email: "matthewscott@example.com",
    mobileNumber: "+1934567890",
    status: "IN_PROCESS"
  },
  {
    id: "18",
    candidateName: "Ava Perez",
    appliedFor: "Content Strategist",
    appliedDate: "2024-11-06",
    email: "avaperez@example.com",
    mobileNumber: "+2045678901",
    status: "REJECTED"
  },
  {
    id: "19",
    candidateName: "Lucas White",
    appliedFor: "Cloud Engineer",
    appliedDate: "2024-10-12",
    email: "lucaswhite@example.com",
    mobileNumber: "+2156789012",
    status: "SELECTED"
  },
  {
    id: "20",
    candidateName: "Mia Robinson",
    appliedFor: "Data Analyst",
    appliedDate: "2024-09-29",
    email: "miarobinson@example.com",
    mobileNumber: "+2267890123",
    status: "IN_PROCESS"
  }
];
