import { Attendance } from "./attendance-columns";

export const data: Attendance[] = [
  {
    id: "1",
    employeeName: "John Doe",
    designation: "Software Engineer",
    type: "REMOTE",
    checkIn: "09:15 AM",
    status: "LATE",
  },
  {
    id: "2",
    employeeName: "Jane Smith",
    designation: "Project Manager",
    type: "OFFICE",
    checkIn: "08:45 AM",
    status: "ON_TIME",
  },
  {
    id: "3",
    employeeName: "Mike Johnson",
    designation: "UI/UX Designer",
    type: "OFFICE",
    checkIn: "09:05 AM",
    status: "LATE",
  },
  {
    id: "4",
    employeeName: "Lisa Brown",
    designation: "Data Analyst",
    type: "REMOTE",
    checkIn: "09:30 AM",
    status: "ON_TIME",
  },
  {
    id: "5",
    employeeName: "Tom Clark",
    designation: "DevOps Engineer",
    type: "OFFICE",
    checkIn: "08:50 AM",
    status: "LATE",
  },
  {
    id: "6",
    employeeName: "Emily Davis",
    designation: "HR Manager",
    type: "REMOTE",
    checkIn: "09:00 AM",
    status: "ON_TIME",
  },
  {
    id: "7",
    employeeName: "David Wilson",
    designation: "Marketing Specialist",
    type: "OFFICE",
    checkIn: "09:20 AM",
    status: "LATE",
  },
  {
    id: "8",
    employeeName: "Samantha Taylor",
    designation: "Sales Representative",
    type: "REMOTE",
    checkIn: "09:10 AM",
    status: "ON_TIME",
  },
  {
    id: "9",
    employeeName: "Kevin White",
    designation: "Network Administrator",
    type: "OFFICE",
    checkIn: "09:05 AM",
    status: "LATE",
  },
  {
    id: "10",
    employeeName: "Sarah Lee",
    designation: "Graphic Designer",
    type: "REMOTE",
    checkIn: "09:25 AM",
    status: "ON_TIME",
  },
  {
    id: "11",
    employeeName: "Brian Hall",
    designation: "Quality Assurance Engineer",
    type: "OFFICE",
    checkIn: "09:15 AM",
    status: "LATE",
  },
  {
    id: "12",
    employeeName: "Christine Martin",
    designation: "Customer Support Specialist",
    type: "REMOTE",
    checkIn: "09:30 AM",
    status: "ON_TIME",
  },
  {
    id: "13",
    employeeName: "Lisa Kim",
    designation: "Software Engineer",
    type: "OFFICE",
    checkIn: "09:05 AM",
    status: "LATE",
  },
  {
    id: "14",
    employeeName: "John Davis",
    designation: "Data Analyst",
    type: "REMOTE",
    checkIn: "09:10 AM",
    status: "ON_TIME",
  },
  {
    id: "15",
    employeeName: "Rebecca Brown",
    designation: "Operations Manager",
    type: "OFFICE",
    checkIn: "09:20 AM",
    status: "LATE",
  },
  {
    id: "16",
    employeeName: "Michael Rodriguez",
    designation: "Product Manager",
    type: "REMOTE",
    checkIn: "09:25 AM",
    status: "ON_TIME",
  },
  {
    id: "17",
    employeeName: "Amanda Johnson",
    designation: "Marketing Manager",
    type: "OFFICE",
    checkIn: "09:15 AM",
    status: "LATE",
  },
  {
    id: "18",
    employeeName: "Richard Thompson",
    designation: "Sales Manager",
    type: "REMOTE",
    checkIn: "09:30 AM",
    status: "ON_TIME",
  },
  {
    id: "19",
    employeeName: "Katherine Jackson",
    designation: "Human Resources Generalist",
    type: "OFFICE",
    checkIn: "09:05 AM",
    status: "LATE",
  },
  {
    id: "20",
    employeeName: "Alexander Garcia",
    designation: "IT Project Manager",
    type: "REMOTE",
    checkIn: "09:10 AM",
    status: "ON_TIME",
  },
];
