import { Payroll } from "./holiday-list-columns";

export const data: Payroll[] = [
  {
    id: "1",
    employeeName: "Alice Johnson",
    ctc: 45000,
    salaryPerMonth: 500,
    deduction: 100,
    status: "COMPLETED", // Example status
  },
  {
    id: "2",
    employeeName: "Bob Smith",
    ctc: 45000,
    salaryPerMonth: 500,
    deduction: 100,
    status: "PENDING",
  },
  {
    id: "3",
    employeeName: "Carla Williams",
    ctc: 45000,
    salaryPerMonth: 500,
    deduction: 100,
    status: "COMPLETED",
  },
  {
    id: "4",
    employeeName: "David Brown",
    ctc: 45000,
    salaryPerMonth: 500,
    deduction: 100,
    status: "PENDING",
  },
  {
    id: "5",
    employeeName: "Ella Davis",
    ctc: 45000,
    salaryPerMonth: 500,
    deduction: 100,
    status: "COMPLETED",
  },
  {
    id: "6",
    employeeName: "Frank Miller",
    ctc: 45000,
    salaryPerMonth: 500,
    deduction: 100,
    status: "COMPLETED",
  },
  {
    id: "7",
    employeeName: "Grace Wilson",
    ctc: 45000,
    salaryPerMonth: 500,
    deduction: 100,
    status: "PENDING",
  },
  {
    id: "8",
    employeeName: "Harry Moore",
    ctc: 45000,
    salaryPerMonth: 500,
    deduction: 100,
    status: "COMPLETED",
  },
  {
    id: "9",
    employeeName: "Isla Taylor",
    ctc: 45000,
    salaryPerMonth: 500,
    deduction: 100,
    status: "PENDING",
  },
  {
    id: "10",
    employeeName: "Jack Thomas",
    ctc: 45000,
    salaryPerMonth: 500,
    deduction: 100,
    status: "COMPLETED",
  },
  {
    id: "11",
    employeeName: "Kara Anderson",
    ctc: 45000,
    salaryPerMonth: 500,
    deduction: 100,
    status: "PENDING",
  },
  {
    id: "12",
    employeeName: "Liam Scott",
    ctc: 45000,
    salaryPerMonth: 500,
    deduction: 100,
    status: "PENDING",
  },
  {
    id: "13",
    employeeName: "Mia Martinez",
    ctc: 45000,
    salaryPerMonth: 500,
    deduction: 100,
    status: "COMPLETED",
  },
  {
    id: "14",
    employeeName: "Nathan Clark",
    ctc: 45000,
    salaryPerMonth: 500,
    deduction: 100,
    status: "COMPLETED",
  },
  {
    id: "15",
    employeeName: "Olivia Lewis",
    ctc: 45000,
    salaryPerMonth: 500,
    deduction: 100,
    status: "PENDING",
  },
  {
    id: "16",
    employeeName: "Paul Young",
    ctc: 45000,
    salaryPerMonth: 500,
    deduction: 100,
    status: "COMPLETED",
  },
  {
    id: "17",
    employeeName: "Quinn Baker",
    ctc: 45000,
    salaryPerMonth: 500,
    deduction: 100,
    status: "COMPLETED",
  },
  {
    id: "18",
    employeeName: "Rachel Green",
    ctc: 45000,
    salaryPerMonth: 500,
    deduction: 100,
    status: "COMPLETED",
  },
  {
    id: "19",
    employeeName: "Sam White",
    ctc: 45000,
    salaryPerMonth: 500,
    deduction: 100,
    status: "PENDING",
  },
  {
    id: "20",
    employeeName: "Tina Black",
    ctc: 45000,
    salaryPerMonth: 500,
    deduction: 100,
    status: "PENDING",
  },
];
